print('\n')
x = input('Press 1 to begin Calculator: ')
if int(x) == 1:
	print('\n'*1)
	print('Press 1 to add ')
	print('Press 2 to subtract ')
	print('Press 3 to multipy ')
	print('Press 4 to divide ')
	print('\n'*1)
	op = input('Select the opration : ')
	print('\n'*1)
	if int(op) == 1 :
		num1 = input('Enter first no  : ')
		num2 = input('enter second no : ')
		num3 = int(num1) + int(num2)
		print('\n'*1)
		print (num1, '+' ,num2 , '=', num3)
	if int(op) == 2 :
		num1 = input('Enter first no  : ')
		num2 = input('enter second no : ')
		num3 = int(num1) - int(num2)
		print('\n'*1)
		print (num1, '-' ,num2 , '=', num3)
	if int(op) == 3 :
		num1 = input('Enter first no  : ')
		num2 = input('enter second no : ')
		num3 = int(num1) * int(num2)
		print('\n'*1)
		print (num1, '*' ,num2 , '=', num3 )
	if int(op) == 4 :
		num1 = input('Enter first no  : ')
		num2 = input('enter second no : ')
		num3 = int(num1) / int(num2)
		print('\n'*1)
		print (num1, '/' ,num2 , '=', num3)
else:
	print('\n')
	print ('Invalid input please try again ')
input()